memes = [
{
    'id':'1',
    'nombre':'Coqueto',
    'autor':'desconocido',
    'fecha_publicacion':'15/02/2020',
    'foto':'img/coqueto.jpeg'
},
{
    'id':'2',
    'nombre':'Ladron',
    'autor':'desconocido',
    'fecha_publicacion':'25/02/2023',
    'foto':'img/ladron.jpeg'
},
{
    'id':'3',
    'nombre':'Juan',
    'autor':'desconocido',
    'fecha_publicacion':'04/04/2021',
    'foto':'img/juan.jpeg'
},
{
    'id':'4',
    'nombre':'Che',
    'autor':'desconocido',
    'fecha_publicacion':'22/12/2022',
    'foto':'img/che.jpeg'
},
]

fondos = [
{
    'id':'1',
    'nombre':'Coqueto',
    'autor':'desconocido',
    'foto':'img/fondo1.jpeg'
},
{
    'id':'2',
    'nombre':'Ladron',
    'autor':'desconocido',
    'foto':'img/fondo2.jpeg'
},
{
    'id':'3',
    'nombre':'Juan',
    'autor':'desconocido',
    'foto':'img/fondo3.jpeg'
},
{
    'id':'4',
    'nombre':'Che',
    'autor':'desconocido',
    'foto':'img/fondo4.jpeg'
},  
]